version: '3.8'

networks:
  prox-network:

services:
  push-api:
    image: nginx
    container_name: api
    ports:
      - 8090:80
    networks:
      - prox-network

  push-web:
    image: grafana/grafana-enterprise
    container_name: web
    ports:
      - 8080:3000
    networks:
      - prox-network

  reverse-proxy:
    image: nginx-reverse-proxy
    container_name: reverse-proxy
    ports:
      - "80:80"
    depends_on:
      - push-api
      - push-web
    networks:
      - prox-network

