version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma
    container_name: uptime-kuma
    volumes:
      - /srv/uptime-kuma/data:/app/data
    ports:
      - "82:3001"
    restart: always